### ISSUE TITLE
Job suggestion

### ISSUE THREAD

**Issue by Natnovok** [javadev/file-manager#1]
Hi!

My name is Natalia, I'm looking for the experts in Java who can create educational projects. We like your project https://github.com/javadev/file-manager and would like to invite you to become our author.

I would be glad to answer all your questions. My e-mail is nf@stepik.org, you can write me in English or Russian.

**Comment by javadev** [comment]
Hi,

Thank you for invitation.

Kind regards, Valentyn

**Comment by Natnovok** [comment]
Hi!

Is it interesting for you to participate?

**Comment by javadev** [comment]
Hi,

I have no experience in create educational projects.

Have a nice day!
